version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: "redis-container"
    ports:
      - "6379:6379"
    networks:
      - todo-network

  web:
    build: .
    container_name: "todo-app"
    ports:
      - "3000:3000"
    networks:
      - todo-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

networks:
  todo-network:
    driver: bridge